### ISSUE TITLE
container does not start

### ISSUE THREAD

**Issue by mohahn** [kc8apf/docker-unifi-video#2]
Using Docker 17.05.0-ce and latest image from hub (kc8apf/unifi-video). Also, I've created container as stated in readme with volume for /config and mapped all ports, but when starting container, I get

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2018-03-15 20:33:28,583 ERROR Unable to locate appender ConsoleErrorAppender for logger uv.stream
2018-03-15 20:33:28,584 ERROR Unable to locate appender ConsoleErrorAppender for logger uv.login
Exception in thread "EmsInitTask" java.lang.NullPointerException
	at com.ubnt.airvision.service.ems.C.do.super(Unknown Source)
	at com.ubnt.airvision.service.ems.C$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mx-shift** [comment]
Thank you for the report.  I just tested creating a new container with Docker 17.12.0-ce and a blank volume for /config.  I see the same output as above.  Despite those errors, the UI does start on port 7080 and initial configuration can be completed successfully.  I see the messages about ConsoleErrorAppender on every start of the container.  I also see those on regular installations on a Debian system.  The EmsInitTask exception seems to only occur when there is no existing configuration.  I'll update the README to explain this.
